task :default do
  sh "bundle install"
  n = 5050
  system "ruby curb_easy.rb #{n}"
  system "ruby curb_multi.rb #{n}"
  system "ruby curb_multi_using_get.rb #{n}" # validate our easier interfaces are efficient
  system "ruby nethttp_test.rb #{n}"
  system "ruby patron_test.rb #{n}"
  system "ruby typhoeus_hydra_test.rb #{n}"
  system "ruby typhoeus_test.rb #{n}"
end
