task :default do
  sh "bundle install"
  n = 2000
  [:curb_easy, :curb_easy14, :curb_multi, :curb_multi_using_get, :nethttp_test, :patron_test, :typhoeus_hydra_test, :typhoeus_test].each do|bench|
    system "ruby #{bench}.rb #{n}"
  end
end
